const SUPABASE_CONFIG = {
    url: "https://wxchapqelujpuwgbffkg.supabase.co",
    anonKey: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4Y2hhcHFlbHVqcHV3Z2JmZmtnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjY2MjgwMjcsImV4cCI6MjA0MjIwNDAyN30.Zz6C7gA9WqQv5NfD4J0K8_m5L2X1Y3Z5",
    useFallback: false,
    adminPhone: "50760000000" // Cambia este número por tu número de WhatsApp de administrador
};

// Dataset inicial completo con los 15 registros extraídos del Excel histórico
const DEMO_TREES = [
    {
        "id": "excel-1",
        "code": "ARB-2024-000001",
        "planter_name": "Domingo Vega Vega",
        "public_name": "Domingo Vega Vega",
        "email": "domingo.vega@oteima.ac.pa",
        "species_name": "Guayacán morado",
        "species_scientific_name": "Handroanthus impetiginosus",
        "planting_date": "2024-09-15",
        "latitude": 7.946295,
        "longitude": -80.77627,
        "province": "Herrera",
        "location_description": "Ocú, Peñas Chatas, Paso Laja",
        "privacy_level": "exact",
        "status": "approved",
        "notes": "Es un árbol nativo de América tropical y es conocido por sus vistosas flores moradas.",
        "primary_photo_url": "https://lh3.googleusercontent.com/d/1PBT6sagBs-OD8zHkv-dGMIHL0YUFIrcp"
    },
    {
        "id": "excel-2",
        "code": "ARB-2024-000002",
        "planter_name": "Fernando Camaño",
        "public_name": "Fernando Camaño",
        "email": "fernando.adames@oteima.ac.pa",
        "species_name": "Guayacán",
        "species_scientific_name": "Guaiacum officinale",
        "planting_date": "2024-09-15",
        "latitude": 8.12218,
        "longitude": -80.966103,
        "province": "Veraguas",
        "location_description": "Barriada la Esmeralda, corregimiento de Canto del Llano",
        "privacy_level": "exact",
        "status": "approved",
        "notes": "Plantón pequeño",
        "primary_photo_url": "https://lh3.googleusercontent.com/d/1VqyPSh1QuvN53CoUZVG_PwlpWd_8tkeg"
    },
    {
        "id": "excel-3",
        "code": "ARB-2024-000003",
        "planter_name": "Anthony Rodriguez",
        "public_name": "Anthony Rodriguez",
        "email": "anthony.rodriguez@oteima.ac.pa",
        "species_name": "Guayacán Morado",
        "species_scientific_name": "Maculís",
        "planting_date": "2024-09-15",
        "latitude": 8.08053,
        "longitude": -80.97686,
        "province": "Veraguas",
        "location_description": "Veraguas, Nuevo Santiago, San Antonio.",
        "privacy_level": "exact",
        "status": "approved",
        "notes": "Es un arbusto de 2 a 5 m de altura, presenta ramas gruesas y torcidas desde la base, con un diámetro del tronco de hasta 20 cm., de copa densa, apretada, perennifolio. Sus flores son pequeñas y violáceas. Sus frutos son cápsulas moradas, tiene numerosas semillas.",
        "primary_photo_url": "https://lh3.googleusercontent.com/d/127loAtCKA4gZ7f0Tq6mBqZjwQpJnu3q5"
    },
    {
        "id": "excel-4",
        "code": "ARB-2024-000004",
        "planter_name": "Kevin Elieser Concepción Rodríguez",
        "public_name": "Kevin Elieser Concepción Rodríguez",
        "email": "kevin.concepcion@oteima.ac.pa",
        "species_name": "Guayacán",
        "species_scientific_name": "Tabebuia rosea",
        "planting_date": "2024-09-15",
        "latitude": 8.299948,
        "longitude": -81.010664,
        "province": "Veraguas",
        "location_description": "La Honda, San Juan, San Francisco, Veraguas, Panamá",
        "privacy_level": "exact",
        "status": "approved",
        "notes": "Este árbol pertenece a la familia Bignoniaceae y es también llamado guayacán rosado, apamate, o ocobo. Es originario de América y se encuentra comúnmente en diversas regiones tropicales, como Colombia y otros países de América Central y del Sur.",
        "primary_photo_url": "https://lh3.googleusercontent.com/d/1jDQt1GUHKcL2GTBtuJ35Ke7_pYHCb4yX"
    },
    {
        "id": "excel-5",
        "code": "ARB-2024-000005",
        "planter_name": "Fatima Escobar",
        "public_name": "Fatima Escobar",
        "email": "fatima.escobar@oteima.ac.pa",
        "species_name": "Guayacán morado",
        "species_scientific_name": "Guaiacum coulteri",
        "planting_date": "2024-09-15",
        "latitude": 7.960288,
        "longitude": -81.174184,
        "province": "Veraguas",
        "location_description": "Rio de Jesus, el cuartillo",
        "privacy_level": "exact",
        "status": "approved",
        "notes": "El guayacán es un árbol tropical conocido por su madera dura y sus flores vistosas.",
        "primary_photo_url": "https://lh3.googleusercontent.com/d/1sxNKjTj9d-19iEbj3ZwtDA2ZW9Sgs5gc"
    },
    {
        "id": "excel-6",
        "code": "ARB-2024-000006",
        "planter_name": "Corina Nicole Lara González",
        "public_name": "Corina Nicole Lara González",
        "email": "corina.lara@oteima.ac.pa",
        "species_name": "Guayacán Morado",
        "species_scientific_name": "Tabebuia  Impetiginosa",
        "planting_date": "2024-09-15",
        "latitude": 8.115386,
        "longitude": -80.949904,
        "province": "Veraguas",
        "location_description": "Distrito de Santiago, corregimiento  Carlos Santana Ávila, lugar El Espino de Santa Rosa",
        "privacy_level": "exact",
        "status": "approved",
        "notes": "El guayacán es un árbol tropical conocido por su madera dura y sus flores vistosas. Aquí tienes algunas recomendaciones para su siembra:\n\n1. Clima: El guayacán requiere un clima cálido y tropical. Idealmente, debe recibir pleno sol y estar en una región con temperaturas que no bajen de 10°C.\n\n2. Suelo: Prefiere suelos bien drenados y ligeramente ácidos a neutros. Evita suelos arcillosos o que retengan demasiada agua, ya que esto puede llevar a problemas de raíz.\n\n3. Preparación del Suelo: Asegúrate de preparar el suelo adecuadamente antes de plantar. Puedes mejorar el drenaje agregando arena o material orgánico.\n\n4. Espaciado: Si plantas más de un árbol, asegúrate de dejarlos a una distancia adecuada, generalmente de 4 a 6 metros entre cada uno, para permitir un buen desarrollo.\n\n5. Riego: Aunque el guayacán es bastante resistente a la sequía una vez establecido, asegúrate de regar bien durante el primer año para fomentar un buen crecimiento. Luego, el riego puede reducirse a medida que el árbol se aclimata.\n\n6. Fertilización: Fertiliza el suelo con un abono balanceado durante la temporada de crecimiento para apoyar el desarrollo saludable del árbol.\n\n7. Mantenimiento: Controla las plagas y enfermedades, y poda el árbol si es necesario para mantener su forma y salud.\n\nRecuerda que el guayacán es un árbol de crecimiento lento, así que ten paciencia mientras se desarrolla.",
        "primary_photo_url": "https://lh3.googleusercontent.com/d/1nINt8LsiABPTLUixwX2GBm9OZPtUnZXC"
    },
    {
        "id": "excel-7",
        "code": "ARB-2024-000007",
        "planter_name": "Angie Hidalgo",
        "public_name": "Angie Hidalgo",
        "email": "angie.milagros@oteima.ac.pa",
        "species_name": "Guayacan morado",
        "species_scientific_name": "Handroanthus impetiginosus",
        "planting_date": "2024-09-15",
        "latitude": 8.016372,
        "longitude": -80.984086,
        "province": "Veraguas",
        "location_description": "Los Hatillos vía La Colorada, Santiago, Veraguas.",
        "privacy_level": "exact",
        "status": "approved",
        "notes": "El guayacán morado (Handroanthus impetiginosus) es un árbol majestuoso y emblemático de América Latina, conocido por su floración espectacular. En temporada, sus ramas se cubren de racimos de flores de un color púrpura intenso, creando un manto de tonos vibrantes que contrastan con el azul del cielo y el verdor de su follaje.",
        "primary_photo_url": "https://lh3.googleusercontent.com/d/1_IWcuUYVDQ1s-9Uy24RSstWPW7EokfL8"
    },
    {
        "id": "excel-8",
        "code": "ARB-2024-000008",
        "planter_name": "Angie Hidalgo",
        "public_name": "Angie Hidalgo",
        "email": "angie.milagros@oteima.ac.pa",
        "species_name": "Guayacan morado",
        "species_scientific_name": "Handroanthus impetiginosus",
        "planting_date": "2024-09-15",
        "latitude": 8.0166,
        "longitude": -80.9843,
        "province": "Veraguas",
        "location_description": "Los Hatillos vía La Colorada, Santiago, Veraguas.",
        "privacy_level": "exact",
        "status": "approved",
        "notes": "El guayacan morado, conocido por su hermosa floración de color violeta o morada. Durante la temporada seca, su copa se llena de vida con un manto de color que contrasta bellamente con el cielo despejado. El guayacán morado simboliza fuerza, resistencia y renovación. Su capacidad para florecer de manera espectacular en la temporada seca, cuando la mayoría de los árboles parecen inertes, lo convierte en un símbolo de perseverancia frente a la adversidad.",
        "primary_photo_url": "https://lh3.googleusercontent.com/d/1LzK31KZMVSdFsdiTlsYsoRvuciLtjO6M"
    },
    {
        "id": "excel-9",
        "code": "ARB-2024-000009",
        "planter_name": "Angie Hidalgo",
        "public_name": "Angie Hidalgo",
        "email": "angie.milagros@oteima.ac.pa",
        "species_name": "Guayacán morado",
        "species_scientific_name": "Handroanthus impetiginosus",
        "planting_date": "2024-09-15",
        "latitude": 8.0161,
        "longitude": -80.9838,
        "province": "Veraguas",
        "location_description": "Los Hatillos vía La Colorada, Santiago, Veraguas.",
        "privacy_level": "exact",
        "status": "approved",
        "notes": "El guayacan morado, conocido por su hermosa floración de color violeta o morada. Durante la temporada seca, su copa se llena de vida con un manto de color que contrasta bellamente con el cielo despejado. El guayacán morado simboliza fuerza, resistencia y renovación. Su capacidad para florecer de manera espectacular en la temporada seca, cuando la mayoría de los árboles parecen inertes, lo convierte en un símbolo de perseverancia frente a la adversidad.",
        "primary_photo_url": "https://lh3.googleusercontent.com/d/1iQSzL1Swm2EcGWvpPU_PHUWyCTXsd7IK"
    },
    {
        "id": "excel-10",
        "code": "ARB-2024-000010",
        "planter_name": "Lia Milena González Pardo",
        "public_name": "Lia Milena González Pardo",
        "email": "liag70921@gmail.com",
        "species_name": "Guayacán",
        "species_scientific_name": "Handroanthus guayacan",
        "planting_date": "2024-09-15",
        "latitude": 8.2995,
        "longitude": -81.01,
        "province": "Veraguas",
        "location_description": "San Francisco Distrito, Barrida El Rosario",
        "privacy_level": "exact",
        "status": "approved",
        "notes": "Árbol pequeño color verde de tamaño pequeño",
        "primary_photo_url": "https://lh3.googleusercontent.com/d/1h8Vwe3I33Tsj4W_G5isH3eHGa5Omos0l"
    },
    {
        "id": "excel-11",
        "code": "ARB-2024-000011",
        "planter_name": "Fernando Barría Cornejo",
        "public_name": "Fernando Barría Cornejo",
        "email": "fernando.barria@oteima.ac.pa",
        "species_name": "Guayacán Morado",
        "species_scientific_name": "Tabebuia impetiginosa",
        "planting_date": "2024-09-15",
        "latitude": 8.225,
        "longitude": -81.365,
        "province": "Veraguas",
        "location_description": "Cañazas, Visvalles, Alto de Los Sánchez",
        "privacy_level": "exact",
        "status": "approved",
        "notes": "Es un árbol de hasta 15 metros de altura, con una corteza grisácea y flores moradas en racimos que florecen en primavera. Su madera es dura y valiosa, y es apreciado por su belleza ornamental.",
        "primary_photo_url": "https://lh3.googleusercontent.com/d/1TAFDv-tB8PbANZb2ohXq1rJZ4Ib7eEdI"
    },
    {
        "id": "excel-12",
        "code": "ARB-2024-000012",
        "planter_name": "Fernando Barría Cornejo",
        "public_name": "Fernando Barría Cornejo",
        "email": "fernando.barria@oteima.ac.pa",
        "species_name": "Guayacán Morado",
        "species_scientific_name": "Tabebuia impetiginosa",
        "planting_date": "2024-09-15",
        "latitude": 8.2253,
        "longitude": -81.3653,
        "province": "Veraguas",
        "location_description": "Cañazas, Visvalles, Alto de Los Sanchez",
        "privacy_level": "exact",
        "status": "approved",
        "notes": "Es un árbol de hasta 15 metros de altura, con una corteza grisácea y flores moradas en racimos que florecen en primavera. Su madera es dura y valiosa, y es apreciado por su belleza ornamental.",
        "primary_photo_url": "https://lh3.googleusercontent.com/d/1Q_o4vsgx3kw0BpJF2UhjQqevY-7ugR_X"
    },
    {
        "id": "excel-13",
        "code": "ARB-2024-000013",
        "planter_name": "John jordán",
        "public_name": "John jordán",
        "email": "john.jordan@oteima.ac.pa",
        "species_name": "Guayacá",
        "species_scientific_name": "Guaiacum senctum",
        "planting_date": "2024-09-15",
        "latitude": 7.9605,
        "longitude": -81.1745,
        "province": "Veraguas",
        "location_description": "Distrito Rio de Jesús",
        "privacy_level": "exact",
        "status": "approved",
        "notes": "El guayacán morado, científicamente conocido como Guaiacum sanctum, es un árbol nativo de América Central y el Caribe, famoso por su madera extremadamente dura y densa, así como por sus hermosas flores moradas",
        "primary_photo_url": "https://lh3.googleusercontent.com/d/1s2JWF9oo-CkgZ7XSm5IDSS63fQIg10cg"
    }
];

const DEMO_SPECIES = [
    {
        "id": "sp-1",
        "common_name": "Guayacan morado",
        "scientific_name": ""
    },
    {
        "id": "sp-2",
        "common_name": "Guayacá",
        "scientific_name": ""
    },
    {
        "id": "sp-3",
        "common_name": "Guayacán",
        "scientific_name": ""
    },
    {
        "id": "sp-4",
        "common_name": "Guayacán Morado",
        "scientific_name": ""
    },
    {
        "id": "sp-5",
        "common_name": "Guayacán morado",
        "scientific_name": ""
    }
];
